# Generated by Django 4.0 on 2021-12-30 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_data',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 12, 30)),
        ),
    ]
