# Generated by Django 4.0 on 2021-12-30 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_vehicle_data_vehicle_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='sjs_dailyprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialy_date', models.DateField(default=datetime.date(2021, 12, 30))),
                ('dialy_profit', models.IntegerField(default=0)),
            ],
        ),
    ]
