# Generated by Django 4.0 on 2021-12-31 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sjs_dailyprofit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='total_income',
        ),
        migrations.DeleteModel(
            name='Vehicle_counts',
        ),
        migrations.AlterField(
            model_name='sjs_dailyprofit',
            name='dialy_date',
            field=models.DateField(default=datetime.date(2021, 12, 31)),
        ),
    ]
